export const LOAD_BUDGET_SUCCESS = 'LOAD_BUDGET_SUCCESS';
export const SAVE_BUDGET_SUCCESS = 'SAVE_BUDGET_SUCCESS';
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS';
export const DELETE_BUDGET_SUCCESS = 'DELETE_BUDGET_SUCCESS';

export const UPDATE_SALARY = 'UPDATE_SALARY';

export const SORT_ITEMS = 'SORT_ITEMS';
export const REVERSE_ITEMS = 'REVERSE_ITEMS';
